### ISSUE TITLE
JSON Output is not a valid JSON

### ISSUE THREAD

**Issue by reflexdemon** [AlDanial/cloc#135]
When I tried to run the tool and requested for `JSON` it does not render a fully valid `json`.

Command-line used
```bash
$ cloc --quiet --diff 2015_07.tar.gz 2015_11.tar.gz  --json
```

For `JSON` we treat the objects as `dictionary` or `maps` in `java`. The below example has duplicate keys like `language`, `files_count`, `comment` etc are being repeated and it make it tough for me to parse the `json` files.
```json
{
    "header": {
        "cloc_url": "github.com/AlDanial/cloc",
        "cloc_version": "1.70",
        "elapsed_seconds": 82.5752959251404,
        "n_files": 3010,
        "n_lines": 570493,
        "files_per_second": 36.4515799341337,
        "lines_per_second": 6908.7611931441
    },
    "same": {
        "language": "HTML",
        "files_count": 13,
        "blank": 0,
        "comment": 222,
        "code": 2476,
        "language": "CSS",
        "files_count": 82,
        "blank": 0,
        "comment": 3509,
        "code": 55917,
        "language": "XML",
        "files_count": 191,
        "blank": 0,
        "comment": 5813,
        "code": 30096,
        "language": "SQL",
        "files_count": 88,
        "blank": 0,
        "comment": 271,
        "code": 8176,
        "language": "JavaScript",
        "files_count": 135,
        "blank": 0,
        "comment": 10431,
        "code": 48486,
        "language": "JSP",
        "files_count": 373,
        "blank": 0,
        "comment": 3110,
        "code": 50635,
        "language": "Java",
        "files_count": 1244,
        "blank": 0,
        "comment": 70481,
        "code": 208948,
        "language": "Ant",
        "files_count": 1,
        "blank": 0,
        "comment": 5,
        "code": 363,
        "language": "JSON",
        "files_count": 8,
        "blank": 0,
        "comment": 0,
        "code": 430,
        "language": "Maven",
        "files_count": 1,
        "blank": 0,
        "comment": 37,
        "code": 1556
    },
    "modified": {
        "language": "HTML",
        "files_count": 2,
        "blank": 0,
        "comment": 0,
        "code": 4,
        "language": "CSS",
        "files_count": 8,
        "blank": 0,
        "comment": 0,
        "code": 35,
        "language": "XML",
        "files_count": 6,
        "blank": 0,
        "comment": 0,
        "code": 1,
        "language": "SQL",
        "files_count": 0,
        "blank": 0,
        "comment": 0,
        "code": 0,
        "language": "JavaScript",
        "files_count": 8,
        "blank": 0,
        "comment": 24,
        "code": 175,
        "language": "JSP",
        "files_count": 50,
        "blank": 0,
        "comment": 126,
        "code": 750,
        "language": "Java",
        "files_count": 70,
        "blank": 0,
        "comment": 159,
        "code": 2605,
        "language": "Ant",
        "files_count": 0,
        "blank": 0,
        "comment": 0,
        "code": 0,
        "language": "JSON",
        "files_count": 0,
        "blank": 0,
        "comment": 0,
        "code": 0,
        "language": "Maven",
        "files_count": 1,
        "blank": 0,
        "comment": 0,
        "code": 10
    },
    "added": {
        "language": "HTML",
        "files_count": 0,
        "blank": 1,
        "comment": 1,
        "code": 5,
        "language": "CSS",
        "files_count": 0,
        "blank": 7,
        "comment": 9,
        "code": 91,
        "language": "XML",
        "files_count": 3,
        "blank": 27,
        "comment": 74,
        "code": 85,
        "language": "SQL",
        "files_count": 8,
        "blank": 36,
        "comment": 50,
        "code": 181,
        "language": "JavaScript",
        "files_count": 2,
        "blank": 110,
        "comment": 173,
        "code": 848,
        "language": "JSP",
        "files_count": 1,
        "blank": 186,
        "comment": 365,
        "code": 2226,
        "language": "Java",
        "files_count": 300,
        "blank": 5696,
        "comment": 1490,
        "code": 19361,
        "language": "Ant",
        "files_count": 0,
        "blank": 0,
        "comment": 0,
        "code": 0,
        "language": "JSON",
        "files_count": 0,
        "blank": 0,
        "comment": 0,
        "code": 0,
        "language": "Maven",
        "files_count": 1,
        "blank": 3,
        "comment": 11,
        "code": 254
    },
    "removed": {
        "language": "HTML",
        "files_count": 0,
        "blank": 8,
        "comment": 0,
        "code": 5,
        "language": "CSS",
        "files_count": 0,
        "blank": 1,
        "comment": 0,
        "code": 7,
        "language": "XML",
        "files_count": 4,
        "blank": 40,
        "comment": 101,
        "code": 156,
        "language": "SQL",
        "files_count": 9,
        "blank": 46,
        "comment": 49,
        "code": 594,
        "language": "JavaScript",
        "files_count": 0,
        "blank": 8,
        "comment": 12,
        "code": 88,
        "language": "JSP",
        "files_count": 0,
        "blank": 12,
        "comment": 106,
        "code": 634,
        "language": "Java",
        "files_count": 399,
        "blank": 6417,
        "comment": 2832,
        "code": 22877,
        "language": "Ant",
        "files_count": 0,
        "blank": 0,
        "comment": 0,
        "code": 0,
        "language": "JSON",
        "files_count": 0,
        "blank": 0,
        "comment": 0,
        "code": 0,
        "language": "Maven",
        "files_count": 2,
        "blank": 8,
        "comment": 13,
        "code": 338
    }
}
```

A recommendation, would be to restructure the `json` as follows,
http://codebeautify.org/xmltojson/cbcbb944

**Comment by AlDanial** [comment]
I fixed a related issue, #127, a couple of months ago.  Please try rerunning with code from the git master.

**Comment by AlDanial** [comment]
Please reopen this if the git master doesn't solve your JSON output issue.

**Comment by reflexdemon** [comment]
Sorry for not responding immediately.

I am looking for brew install to have the latest. It looks like the brew package is still not published with latest.
