### ISSUE TITLE
assertion failed: open my_perl 

### ISSUE THREAD

**Issue by dmmacs** [AlDanial/cloc#21]
I use this tool as part of my build process within a Jenkins server. I run 4 build variations every night when there are code changes.. Over the last 10 times the 4 variations have run, there have been 2 failures (out of 40 executions of cloc). On the most recent instance, the 1st of the 4 variations failed and the remaining 3 were successful.

EDIT: The "assertion failed" always happens on the Jenkins server but never happens when we run on the command line directly but does not cause the build to fail. Added additional line showing the Unknown exception that the build fails on. Don't know if the error is at the end of the first command line or the beginning of the second command line. 

I get the following error message when this occurs. 
`23:51:26 assertion failed: open my_perl`
`23:51:26 assertion failed: MZ magic bytes`
`23:51:26 assertion failed: PE header`
`23:51:26 assertion failed: IMAGE_NT_OPTIONAL_HDR_MAGIC`
`23:51:26 amk E457: ["makefile" 158/0] uncaught 'Unknown' exception (ffffffff) while executing 'PR11940_GEN7_2_PostBuild'`

We run the command twice to get both the detailed and summary data:
`cloc-1.62 --by-file --progress-rate=0 --quiet --report-file=PR11940_cloc_report.xml --list-file=PR11940_cloc.txt`
`cloc-1.62 --progress-rate=0 --quiet --report-file=PR11940_GEN7_2_cloc_report.txt --list-file=PR11940_GEN7_2_cloc.txt`

In the process of upgrading to v1.64 to see if problem repeats but also would like to be able to capture some additional debug information if that would be helpful to finding the root cause of the issue

**Comment by AlDanial** [comment]
There were definitely bugs in 1.62 that were fixed by 1.64.  In fact, the current development version is better than both of those.  Please report back if you hit problems with newer releases.

**Comment by dmmacs** [comment]
Updated to v1.64, still get the assertions (no Unknown exceptions yet). Added -v=10 to the command line, the last few lines of the output is:

13:27:02 rm_comments file=C:\Jenkins\workspace\Core_Trunk_Git_CI\Sources\Utils\UtlSm\UtlSm.h sub=remove_inline
13:27:02 -> remove_inline(pattern=//.*$)
13:27:02 -> remove_matches_2re(pattern=^\s*$,\\$)
13:27:02 <- remove_matches_2re
13:27:02 <- rm_comments
13:27:02 <- call_counter(142, 19, 101)
13:27:02 -> generate_report
13:27:02 -> output_header
13:27:02 <- output_header
13:27:02 <- generate_report
13:27:02 -> write_file(EMULATOR\PR11940_GEN7_2_cloc_report.txt)
13:27:02 <- write_file
13:27:02 assertion failed: open my_perl
13:27:02 assertion failed: MZ magic bytes
13:27:02 assertion failed: PE header
13:27:02 assertion failed: IMAGE_NT_OPTIONAL_HDR_MAGIC

The Jenkins job runs the 4 variations in parallel. On Windows 7, just in case that makes a difference. 

Additional information: we ran the perl script directly using Strawberry Perl 5.22.01 and the assertion failed line does not show up. This is not our preferred solution because we would have to ensure that the engineers all the had the correct version of Perl installed or add the necessary Perl files to our build process.

**Comment by AlDanial** [comment]
Cloc has no assert calls, so the "assertion failed" is coming from somewhere else.  My theory is you are hitting a file system write race condition due to your parallel runs.

Do you see assertion errors when you restrict Jenkins to run only one instance of cloc at a time?
Do you run the Perl source with 4 parallel instances too?  If this answer is yes and it runs correctly, perhaps there's a quirk with the executable.  Note, now that you have Strawberry Perl, you can create your own executable from the cloc source (https://github.com/AlDanial/cloc#building_exe).
