### ISSUE TITLE
Cloc from MacOS Homebrew formula crashing

### ISSUE THREAD

**Issue by chernals** [AlDanial/cloc#426]
I believe my upgrade to Catalina and/or a newer version of Perl caused this. This is most probably not an issue with Cloc itself, however, any pointer toward a possible solution would be appreciated.

```
~ » brew info cloc
cloc: stable 1.84 (bottled), HEAD
Statistics utility to count lines of code
https://github.com/AlDanial/cloc/
/usr/local/Cellar/cloc/1.84 (89 files, 1.6MB) *
  Poured from bottle on 2019-10-26 at 13:20:06
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/cloc.rb
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 9,772 (30 days), 17,064 (90 days), 57,563 (365 days)
install_on_request: 8,924 (30 days), 15,913 (90 days), 53,275 (365 days)
build_error: 0 (30 days)
~ » cloc
Can't locate Moo/Role.pm in @INC (you may need to install the Moo::Role module) (@INC contains: /usr/local/Cellar/cloc/1.84/libexec/lib/perl5/darwin-thread-multi-2level /usr/local/Cellar/cloc/1.84/libexec/lib/perl5 /usr/local/Cellar/perl/5.30.0/lib/perl5/site_perl/5.30.0/darwin-thread-multi-2level /usr/local/Cellar/perl/5.30.0/lib/perl5/site_perl/5.30.0 /usr/local/Cellar/perl/5.30.0/lib/perl5/5.30.0/darwin-thread-multi-2level /usr/local/Cellar/perl/5.30.0/lib/perl5/5.30.0 /usr/local/lib/perl5/site_perl/5.30.0) at /usr/local/Cellar/cloc/1.84/libexec/lib/perl5/Parallel/ForkManager/Child.pm line 12.
BEGIN failed--compilation aborted at /usr/local/Cellar/cloc/1.84/libexec/lib/perl5/Parallel/ForkManager/Child.pm line 12.
Compilation failed in require at /usr/local/Cellar/cloc/1.84/libexec/lib/perl5/Parallel/ForkManager.pm line 12.
BEGIN failed--compilation aborted at /usr/local/Cellar/cloc/1.84/libexec/lib/perl5/Parallel/ForkManager.pm line 12.
Compilation failed in require at /usr/local/Cellar/cloc/1.84/libexec/bin/cloc line 879.
BEGIN failed--compilation aborted at /usr/local/Cellar/cloc/1.84/libexec/bin/cloc line 879.
~ » perl --version

This is perl 5, version 30, subversion 0 (v5.30.0) built for darwin-thread-multi-2level

Copyright 1987-2019, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

```

**Comment by AlDanial** [comment]
Here's what it looks like to me:  the brew definition for cloc needs to add a (new?) dependency on the ``Moo::Role`` Perl module which appears as a dependency for ``Parallel::ForkManager`` as shown on CPAN (https://metacpan.org/pod/Parallel::ForkManager).

The Unix (+MacOS) version of cloc uses ``Parallel::ForkManager`` to enable running on multiple cores with the ``--processes=N`` switch.

The work-around is to use the generic version of cloc from https://github.com/AlDanial/cloc/releases/download/1.84/cloc-1.84.pl which does not depend on ``Parallel::ForkManager`` (but is limited to running on one core).

**Comment by alichtman** [comment]
> I believe my upgrade to Catalina

It crashes for me on Mojave, too. @AlDanial's workaround worked for me.

**Comment by chernals** [comment]
@AlDanial  @alichtman  Thanks; it took me a while to get familiar with CPAN and how to install the packages at the proper location on Mac, but this is solved.

I should edit the brew formula and create a pull request.

**Comment by TheKnarf** [comment]
Still an issue, `cloc` stopped working for me on Mjoave after running `brew upgrade`. When will there be a fix?

**Comment by josephjang** [comment]
Installing `Moo::Role` solved the problem as mentioned by the others.
```
$ cpan -I Moo::Role
```

**Comment by chucker** [comment]
This was apparently fixed in https://github.com/Homebrew/homebrew-core/pull/49490, but I still ran into it.

**Comment by tombruijn** [comment]
I had to reinstall cloc with `brew update && brew reinstall cloc` because the linked homebrew PR doesn't bump the cloc version that it gets marked as updated.

**Comment by richardsimkins** [comment]
`brew install cloc` hangs forever on the output `==> Downloading https://ghcr.io/v2/homebrew/core/cloc/manifests/1.92`

**Comment by AlDanial** [comment]
I can't speak to  problems related to ``brew install cloc`` as I don't manage the cloc package for ``brew``.  The work-around is to download and use the original, https://github.com/AlDanial/cloc/releases/download/v1.92/cloc-1.92.pl.

**Comment by richardsimkins** [comment]
Thank you for the suggested work around. The issue with brew appears to be resolved now so I will use that.

**Comment by AlDanial** [comment]
I'm glad to hear it.  This issue's been open a long time!
